version: '3'
services:
  angular-app:
    build: ./api-validator-client
    ports:
      - "4200:4200"
    networks:
      - my-network
  spring-boot-app:
    build: ./api-validator
    ports:
      - "8080:8080"
    environment:
      - db.user=root
      - db.password=
      - db.address=mysql-db
      - db.port=3306
      - db.name=validator-test
    networks:
      - my-network
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: validator-test
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
